<a href="https://colab.research.google.com/github/armandossrecife/teste/blob/main/Analise_sbes_2012_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://raw.githubusercontent.com/armandossrecife/teste/main/sbes2022-dataset.csv

--2023-03-23 19:47:17--  https://raw.githubusercontent.com/armandossrecife/teste/main/sbes2022-dataset.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1027444 (1003K) [text/plain]
Saving to: ‘sbes2022-dataset.csv’

sbes2022-dataset.cs 100%[===================>]   1003K  --.-KB/s    in 0.03s

2023-03-23 19:47:17 (35.5 MB/s) - ‘sbes2022-dataset.csv’ saved [1027444/1027444]

In [2]:
import pandas as pd

In [3]:
df_sbes_10i = pd.read_csv('sbes2022-dataset.csv')
df_sbes_10i

,paper_year,paper_id,paper_title,paper_authors,paper_language,citation_id,citation_info,citation_year,citation_validity,citation_origin,citation_type,citation_scope,citation_longevity
0,2010,1,A Study of the Relationships between Source Co...,"Paulo Meirelles, Carlos Denner Santos Jr., Joã...",english,1.0,"Steinmacher, Igor, Tayana Conte, Marco Aurélio...",2015,valid,community_nat,conference,international,5
1,2010,1,A Study of the Relationships between Source Co...,"Paulo Meirelles, Carlos Denner Santos Jr., Joã...",english,2.0,"Santos, Carlos, George Kuk, Fabio Kon, and Joh...",2013,valid,self,journal,international,3
2,2010,1,A Study of the Relationships between Source Co...,"Paulo Meirelles, Carlos Denner Santos Jr., Joã...",english,3.0,"de O Melo, Claudia, Viviane Santos, Eduardo Ka...",2013,valid,self,journal,national_other,3
3,2010,1,A Study of the Relationships between Source Co...,"Paulo Meirelles, Carlos Denner Santos Jr., Joã...",english,4.0,"Steinmacher, Igor, Igor Scaliante Wiese, Tayan...",2014,valid,community_nat,conference,international,4
4,2010,1,A Study of the Relationships between Source Co...,"Paulo Meirelles, Carlos Denner Santos Jr., Joã...",english,5.0,"Rudolf Ferenc, Péter Hegedűs, Tibor Gyimóthy. ...",2014,valid,int_external,other,international,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,2020,41,Using Stack Overflow to Assess Technical Debt ...,"Eliakim Gama, Sávio Freire, Manoel G. Mendonça...",english,1.0,"Costa, Diego, Mariela Cortés, and Eliakim Gama...",2021,valid,self,conference,national_sbes,1
2249,2020,42,Using Surveys to Build-up Empirical Evidence o...,"Lucinéia Souza, Sávio Freire, Verusca Rocha, N...",english,1.0,"Pérez, Boris, Camilo Castellanos, Darío Correa...",2021,valid,self,journal,international,1
2250,2020,42,Using Surveys to Build-up Empirical Evidence o...,"Lucinéia Souza, Sávio Freire, Verusca Rocha, N...",english,2.0,"Perez Gutierrez, Boris Rainiero. ""REBEL: A Sem...",2021,valid,int_external,msc_phd,international,1
2251,2020,43,What causes merge conflicts?,"José William Menezes, Bruno Trindade, João Fel...",english,1.0,"Costa, Catarina, José Menezes, Bruno Trindade,...",2021,valid,self,conference,national_sbes,1
2252,2020,43,What causes merge conflicts?,"José William Menezes, Bruno Trindade, João Fel...",english,2.0,"Menezes, José William, Bruno Trindade, João Fe...",2021,valid,self,journal,national_other,1

In [4]:
df_sbes_10i.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   paper_year          2253 non-null   int64
 1   paper_id            2253 non-null   int64
 2   paper_title         2253 non-null   object
 3   paper_authors       2253 non-null   object
 4   paper_language      2253 non-null   object
 5   citation_id         2251 non-null   float64
 6   citation_info       2253 non-null   object
 7   citation_year       2253 non-null   int64
 8   citation_validity   2253 non-null   object
 9   citation_origin     2187 non-null   object
 10  citation_type       2198 non-null   object
 11  citation_scope      2189 non-null   object
 12  citation_longevity  2253 non-null   int64
dtypes: float64(1), int64(4), object(8)
memory usage: 228.9+ KB

In [15]:
my_df = df_sbes_10i.copy()
my_df = my_df[['paper_year', 'paper_title', 'paper_authors', 'paper_language', 'citation_year']]
my_df.head(5)

,paper_year,paper_title,paper_authors,paper_language,citation_year
0,2010,A Study of the Relationships between Source Co...,"Paulo Meirelles, Carlos Denner Santos Jr., Joã...",english,2015
1,2010,A Study of the Relationships between Source Co...,"Paulo Meirelles, Carlos Denner Santos Jr., Joã...",english,2013
2,2010,A Study of the Relationships between Source Co...,"Paulo Meirelles, Carlos Denner Santos Jr., Joã...",english,2013
3,2010,A Study of the Relationships between Source Co...,"Paulo Meirelles, Carlos Denner Santos Jr., Joã...",english,2014
4,2010,A Study of the Relationships between Source Co...,"Paulo Meirelles, Carlos Denner Santos Jr., Joã...",english,2014

In [17]:
my_df.drop_duplicates(inplace=True)

In [18]:
my_df['paper_language'].value_counts()

english       677
portuguese    187
Name: paper_language, dtype: int64

In [19]:
conta_linguagem = my_df['paper_language'].value_counts()
conta_linguagem

english       677
portuguese    187
Name: paper_language, dtype: int64

In [20]:
total_linguagem = conta_linguagem['english'] + conta_linguagem['portuguese']
print(f"Total: {total_linguagem}, inglês: {conta_linguagem['english']}, português: {conta_linguagem['portuguese']}")
print(f"inglês: {round(conta_linguagem['english']/total_linguagem, 2)}, português: {round(conta_linguagem['portuguese']/total_linguagem,2)}")

Total: 864, inglês: 677, português: 187
inglês: 0.78, português: 0.22