<a href="https://colab.research.google.com/github/armandossrecife/teste/blob/main/av1tes20251.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Coleta dos Dados

In [1]:
!rm *.csv

In [2]:
!wget https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/alunostes20251.csv

--2025-05-21 19:52:20--  https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/alunostes20251.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 941 [text/plain]
Saving to: ‘alunostes20251.csv’

alunostes20251.csv  100%[===================>]     941  --.-KB/s    in 0s

2025-05-21 19:52:20 (10.7 MB/s) - ‘alunostes20251.csv’ saved [941/941]

In [3]:
!wget https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/lista1tes20251.csv

--2025-05-21 19:52:20--  https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/lista1tes20251.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 803 [text/plain]
Saving to: ‘lista1tes20251.csv’

lista1tes20251.csv  100%[===================>]     803  --.-KB/s    in 0s

2025-05-21 19:52:21 (33.6 MB/s) - ‘lista1tes20251.csv’ saved [803/803]

In [4]:
!wget https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/lista2tes20251.csv

--2025-05-21 19:52:21--  https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/lista2tes20251.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 731 [text/plain]
Saving to: ‘lista2tes20251.csv’

lista2tes20251.csv  100%[===================>]     731  --.-KB/s    in 0s

2025-05-21 19:52:21 (42.7 MB/s) - ‘lista2tes20251.csv’ saved [731/731]

In [5]:
!wget https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/lista3tes20251.csv

--2025-05-21 19:52:21--  https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/lista3tes20251.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 905 [text/plain]
Saving to: ‘lista3tes20251.csv’

lista3tes20251.csv  100%[===================>]     905  --.-KB/s    in 0s

2025-05-21 19:52:21 (23.7 MB/s) - ‘lista3tes20251.csv’ saved [905/905]

In [6]:
!wget https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/lista4tes20251.csv

--2025-05-21 19:52:21--  https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/lista4tes20251.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607 [text/plain]
Saving to: ‘lista4tes20251.csv’

lista4tes20251.csv  100%[===================>]     607  --.-KB/s    in 0s

2025-05-21 19:52:21 (38.0 MB/s) - ‘lista4tes20251.csv’ saved [607/607]

# Cria os dataframes

In [7]:
import pandas as pd

In [8]:
df_alunos_tes = pd.read_csv("alunostes20251.csv", sep=',')
df_alunos_tes

      MATRICULA                                               NOME
0   20229004551                    AVERINALDO OSCAR DA CRUZ JUNIOR
1   20229006215                           BENJAMIM DE PINHO SABINO
2   20229004112                  CAIO BURTON ALVES ALENCAR PEREIRA
3   20229011091        CARLOS DANIEL PORTELA SOARES DA SILVA ROCHA
4   20229004598                             EMERY FREITAS MORICONI
5   20219043930                  FELIPE HOLANDA AGUIAR DE CARVALHO
6   20159041965                 GILVANEIDE DE SOUSA NOBRE FE FILHA
7   20229002181                           GUILBERTH DE SOUSA BRUNO
8   20219015767                              GUILHERME TORRES MELO
9   20169053736                              IARHEL ANDRADE SABOJA
10  20189003400  JACOB ALEXANDRE RUFINO LEONCIO CAVALCANTE DE A...
11  20179005948                   JOÃO PEDRO DOS SANTOS PATROCINIO
12  20219041319                             JORDANA BEZERRA FRANCA
13  20229001200                               LAILA TEIXEIRA LOPES
14  20179024317                          LEONIDAS PEREIRA DE ABREU
15  20209018344          NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA
16  20229001406                         RAFFAEL FERREIRA FERNANDES
17  20209061200                 RODRIGO EDUARDO DE ALENCAR MARQUES
18  20189002378                               SAMUEL DA SILVA CRUZ
19  20169040943                          SILVESTRE MOURA RODRIGUES
20  20189007795                  VIVAL JOSE SEIXAS DE CASTRO FILHO
21  20229006206                           WESLEY DE SOUSA COUTINHO

In [9]:
df_alunos_tes['l1'] = 0
df_alunos_tes['l2'] = 0
df_alunos_tes['l3'] = 0
df_alunos_tes['l4'] = 0
df_alunos_tes

,MATRICULA,NOME,l1,l2,l3,l4
0,20229004551,AVERINALDO OSCAR DA CRUZ JUNIOR,0,0,0,0
1,20229006215,BENJAMIM DE PINHO SABINO,0,0,0,0
2,20229004112,CAIO BURTON ALVES ALENCAR PEREIRA,0,0,0,0
3,20229011091,CARLOS DANIEL PORTELA SOARES DA SILVA ROCHA,0,0,0,0
4,20229004598,EMERY FREITAS MORICONI,0,0,0,0
5,20219043930,FELIPE HOLANDA AGUIAR DE CARVALHO,0,0,0,0
6,20159041965,GILVANEIDE DE SOUSA NOBRE FE FILHA,0,0,0,0
7,20229002181,GUILBERTH DE SOUSA BRUNO,0,0,0,0
8,20219015767,GUILHERME TORRES MELO,0,0,0,0
9,20169053736,IARHEL ANDRADE SABOJA,0,0,0,0
10,20189003400,JACOB ALEXANDRE RUFINO LEONCIO CAVALCANTE DE A...,0,0,0,0
11,20179005948,JOÃO PEDRO DOS SANTOS PATROCINIO,0,0,0,0
12,20219041319,JORDANA BEZERRA FRANCA,0,0,0,0
13,20229001200,LAILA TEIXEIRA LOPES,0,0,0,0
14,20179024317,LEONIDAS PEREIRA DE ABREU,0,0,0,0
15,20209018344,NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA,0,0,0,0
16,20229001406,RAFFAEL FERREIRA FERNANDES,0,0,0,0
17,20209061200,RODRIGO EDUARDO DE ALENCAR MARQUES,0,0,0,0
18,20189002378,SAMUEL DA SILVA CRUZ,0,0,0,0
19,20169040943,SILVESTRE MOURA RODRIGUES,0,0,0,0
20,20189007795,VIVAL JOSE SEIXAS DE CASTRO FILHO,0,0,0,0
21,20229006206,WESLEY DE SOUSA COUTINHO,0,0,0,0

In [10]:
df_alunos_tes['l4'] = 0

In [11]:
df_lista1 = pd.read_csv('lista1tes20251.csv', sep=',')
df_lista1['NOME'] = df_lista1.Aluno
df_lista2 = pd.read_csv('lista2tes20251.csv', sep=',')
df_lista2['NOME'] = df_lista2.Aluno
df_lista3 = pd.read_csv('lista3tes20251.csv', sep=',')
df_lista3['NOME'] = df_lista3.Aluno
df_lista4 = pd.read_csv('lista4tes20251.csv', sep=',')
df_lista4['NOME'] = df_lista4.Aluno

In [12]:
lista1 = df_lista1.Aluno.to_list()
print(len(lista1), lista1)

14 ['AVERINALDO OSCAR DA CRUZ JUNIOR', 'BENJAMIM DE PINHO SABINO', 'CAIO BURTON ALVES ALENCAR PEREIRA', 'CARLOS DANIEL PORTELA SOARES DA SILVA ROCHA', 'EMERY FREITAS MORICONI', 'GUILBERTH DE SOUSA BRUNO', 'GUILHERME TORRES MELO', 'IARHEL ANDRADE SABOIA', 'JACOB ALEXANDRE RUFINO LEONCIO CAVALCANTE DE ARAUJO', 'JORDANA BEZERRA FRANCA', 'NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA', 'RAFFAEL FERREIRA FERNANDES', 'RODRIGO EDUARDO DE ALENCAR MARQUES', 'SAMUEL DA SILVA CRUZ']

In [13]:
lista2 = df_lista2.Aluno.to_list()
print(len(lista2), lista2)

14 ['AVERINALDO OSCAR DA CRUZ JUNIOR', 'BENJAMIM DE PINHO SABINO', 'CAIO BURTON ALVES ALENCAR PEREIRA', 'CARLOS DANIEL PORTELA SOARES DA SILVA ROCHA', 'EMERY FREITAS MORICONI', 'FELIPE HOLANDA AGUIAR DE CARVALHO', 'GUILBERTH DE SOUSA BRUNO', 'GUILHERME TORRES MELO', 'IARHEL ANDRADE SABOIA', 'JOAO PEDRO DOS SANTOS PATROCINIO', 'JORDANA BEZERRA FRANCA', 'LAILA TEIXEIRA LOPES', 'NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA', 'RAFFAEL FERREIRA FERNANDES']

In [14]:
lista3 = df_lista3.Aluno.to_list()
print(len(lista3), lista3)

17 ['AVERINALDO OSCAR DA CRUZ JUNIOR', 'BENJAMIM DE PINHO SABINO', 'CAIO BURTON ALVES ALENCAR PEREIRA', 'CARLOS DANIEL PORTELA SOARES DA SILVA ROCHA', 'EMERY FREITAS MORICONI', 'FELIPE HOLANDA AGUIAR DE CARVALHO', 'GUILBERTH DE SOUSA BRUNO', 'GUILHERME TORRES MELO', 'JACOB ALEXANDRE RUFINO LEONCIO CAVALCANTE DE ARAUJO', 'JOAO PEDRO DOS SANTOS PATROCINIO', 'JORDANA BEZERRA FRANCA', 'LAILA TEIXEIRA LOPES', 'NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA', 'RAFFAEL FERREIRA FERNANDES', 'RODRIGO EDUARDO DE ALENCAR MARQUES', 'SAMUEL DA SILVA CRUZ', 'WESLEY DE SOUSA COUTINHO']

In [15]:
lista4 = df_lista4.Aluno.to_list()
print(len(lista4), lista4)

12 ['AVERINALDO OSCAR DA CRUZ JUNIOR', 'EMERY FREITAS MORICONI', 'FELIPE HOLANDA AGUIAR DE CARVALHO', 'GUILBERTH DE SOUSA BRUNO', 'GUILHERME TORRES MELO', 'IARHEL ANDRADE SABOIA', 'JOAO PEDRO DOS SANTOS PATROCINIO', 'JORDANA BEZERRA FRANCA', 'LAILA TEIXEIRA LOPES', 'NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA', 'RAFFAEL FERREIRA FERNANDES', 'SAMUEL DA SILVA CRUZ']

# Faz as comparações

In [16]:
# prompt: Crie uma função que dado o dataframe df_alunos_tes compare se NOME aparece na lista1 de nomes, se fim atualiza a coluna l1 para 1 se não atualiza a coluna l1 para 0

def comparar_nomes_lista(df_alunos, lista_nomes, avaliacao):
  if avaliacao=='l1':
    df_alunos['l1'] = df_alunos['NOME'].apply(lambda x: 1 if x in lista_nomes else 0)
  if avaliacao=='l2':
    df_alunos['l2'] = df_alunos['NOME'].apply(lambda x: 1 if x in lista_nomes else 0)
  if avaliacao=='l3':
    df_alunos['l3'] = df_alunos['NOME'].apply(lambda x: 1 if x in lista_nomes else 0)
  if avaliacao=='l4':
    df_alunos['l4'] = df_alunos['NOME'].apply(lambda x: 1 if x in lista_nomes else 0)

  return df_alunos

In [17]:
df_alunos_tes = comparar_nomes_lista(df_alunos_tes, lista1, 'l1')
df_alunos_tes = comparar_nomes_lista(df_alunos_tes, lista2, 'l2')
df_alunos_tes = comparar_nomes_lista(df_alunos_tes, lista3, 'l3')
df_alunos_tes = comparar_nomes_lista(df_alunos_tes, lista4, 'l4')

In [18]:
df_alunos_tes

,MATRICULA,NOME,l1,l2,l3,l4
0,20229004551,AVERINALDO OSCAR DA CRUZ JUNIOR,1,1,1,1
1,20229006215,BENJAMIM DE PINHO SABINO,1,1,1,0
2,20229004112,CAIO BURTON ALVES ALENCAR PEREIRA,1,1,1,0
3,20229011091,CARLOS DANIEL PORTELA SOARES DA SILVA ROCHA,1,1,1,0
4,20229004598,EMERY FREITAS MORICONI,1,1,1,1
5,20219043930,FELIPE HOLANDA AGUIAR DE CARVALHO,0,1,1,1
6,20159041965,GILVANEIDE DE SOUSA NOBRE FE FILHA,0,0,0,0
7,20229002181,GUILBERTH DE SOUSA BRUNO,1,1,1,1
8,20219015767,GUILHERME TORRES MELO,1,1,1,1
9,20169053736,IARHEL ANDRADE SABOJA,0,0,0,0
10,20189003400,JACOB ALEXANDRE RUFINO LEONCIO CAVALCANTE DE A...,1,0,1,0
11,20179005948,JOÃO PEDRO DOS SANTOS PATROCINIO,0,0,0,0
12,20219041319,JORDANA BEZERRA FRANCA,1,1,1,1
13,20229001200,LAILA TEIXEIRA LOPES,0,1,1,1
14,20179024317,LEONIDAS PEREIRA DE ABREU,0,0,0,0
15,20209018344,NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA,1,1,1,1
16,20229001406,RAFFAEL FERREIRA FERNANDES,1,1,1,1
17,20209061200,RODRIGO EDUARDO DE ALENCAR MARQUES,1,0,1,0
18,20189002378,SAMUEL DA SILVA CRUZ,1,0,1,1
19,20169040943,SILVESTRE MOURA RODRIGUES,0,0,0,0
20,20189007795,VIVAL JOSE SEIXAS DE CASTRO FILHO,0,0,0,0
21,20229006206,WESLEY DE SOUSA COUTINHO,0,0,1,0

In [19]:
# prompt: Como gerar uma nova coluna primeiro_nome no dataframe df_alunos_tes usando a coluna NOME

df_alunos_tes['primeiro_nome'] = df_alunos_tes['NOME'].apply(lambda x: x.split(' ')[0])
df_alunos_tes

,MATRICULA,NOME,l1,l2,l3,l4,primeiro_nome
0,20229004551,AVERINALDO OSCAR DA CRUZ JUNIOR,1,1,1,1,AVERINALDO
1,20229006215,BENJAMIM DE PINHO SABINO,1,1,1,0,BENJAMIM
2,20229004112,CAIO BURTON ALVES ALENCAR PEREIRA,1,1,1,0,CAIO
3,20229011091,CARLOS DANIEL PORTELA SOARES DA SILVA ROCHA,1,1,1,0,CARLOS
4,20229004598,EMERY FREITAS MORICONI,1,1,1,1,EMERY
5,20219043930,FELIPE HOLANDA AGUIAR DE CARVALHO,0,1,1,1,FELIPE
6,20159041965,GILVANEIDE DE SOUSA NOBRE FE FILHA,0,0,0,0,GILVANEIDE
7,20229002181,GUILBERTH DE SOUSA BRUNO,1,1,1,1,GUILBERTH
8,20219015767,GUILHERME TORRES MELO,1,1,1,1,GUILHERME
9,20169053736,IARHEL ANDRADE SABOJA,0,0,0,0,IARHEL
10,20189003400,JACOB ALEXANDRE RUFINO LEONCIO CAVALCANTE DE A...,1,0,1,0,JACOB
11,20179005948,JOÃO PEDRO DOS SANTOS PATROCINIO,0,0,0,0,JOÃO
12,20219041319,JORDANA BEZERRA FRANCA,1,1,1,1,JORDANA
13,20229001200,LAILA TEIXEIRA LOPES,0,1,1,1,LAILA
14,20179024317,LEONIDAS PEREIRA DE ABREU,0,0,0,0,LEONIDAS
15,20209018344,NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA,1,1,1,1,NIVALDO
16,20229001406,RAFFAEL FERREIRA FERNANDES,1,1,1,1,RAFFAEL
17,20209061200,RODRIGO EDUARDO DE ALENCAR MARQUES,1,0,1,0,RODRIGO
18,20189002378,SAMUEL DA SILVA CRUZ,1,0,1,1,SAMUEL
19,20169040943,SILVESTRE MOURA RODRIGUES,0,0,0,0,SILVESTRE
20,20189007795,VIVAL JOSE SEIXAS DE CASTRO FILHO,0,0,0,0,VIVAL
21,20229006206,WESLEY DE SOUSA COUTINHO,0,0,1,0,WESLEY

In [20]:
df_alunos_tes.to_excel('alunostes20251av1.xlsx')

In [21]:
def testar_nome_nas_listas(nome):
  t1, t2, t3, t4 = '', '', '', ''
  for i in lista1:
    if nome in i:
      t1 = 'l1 OK!'
  for i in lista2:
    if nome in i:
      t2 = 'l2 OK!'
  for i in lista3:
    if nome in i:
      t3 = 'l3 OK!'
  for i in lista4:
    if nome in i:
      t4 = 'l4 OK!'
  resultado = t1 + ',' + t2 + ',' + t3 + ',' + t4
  return resultado

In [22]:
df_alunos_tes['listas'] = df_alunos_tes['primeiro_nome'].apply(lambda x: testar_nome_nas_listas(x))
df_alunos_tes

,MATRICULA,NOME,l1,l2,l3,l4,primeiro_nome,listas
0,20229004551,AVERINALDO OSCAR DA CRUZ JUNIOR,1,1,1,1,AVERINALDO,"l1 OK!,l2 OK!,l3 OK!,l4 OK!"
1,20229006215,BENJAMIM DE PINHO SABINO,1,1,1,0,BENJAMIM,"l1 OK!,l2 OK!,l3 OK!,"
2,20229004112,CAIO BURTON ALVES ALENCAR PEREIRA,1,1,1,0,CAIO,"l1 OK!,l2 OK!,l3 OK!,"
3,20229011091,CARLOS DANIEL PORTELA SOARES DA SILVA ROCHA,1,1,1,0,CARLOS,"l1 OK!,l2 OK!,l3 OK!,"
4,20229004598,EMERY FREITAS MORICONI,1,1,1,1,EMERY,"l1 OK!,l2 OK!,l3 OK!,l4 OK!"
5,20219043930,FELIPE HOLANDA AGUIAR DE CARVALHO,0,1,1,1,FELIPE,",l2 OK!,l3 OK!,l4 OK!"
6,20159041965,GILVANEIDE DE SOUSA NOBRE FE FILHA,0,0,0,0,GILVANEIDE,",,,"
7,20229002181,GUILBERTH DE SOUSA BRUNO,1,1,1,1,GUILBERTH,"l1 OK!,l2 OK!,l3 OK!,l4 OK!"
8,20219015767,GUILHERME TORRES MELO,1,1,1,1,GUILHERME,"l1 OK!,l2 OK!,l3 OK!,l4 OK!"
9,20169053736,IARHEL ANDRADE SABOJA,0,0,0,0,IARHEL,"l1 OK!,l2 OK!,,l4 OK!"
10,20189003400,JACOB ALEXANDRE RUFINO LEONCIO CAVALCANTE DE A...,1,0,1,0,JACOB,"l1 OK!,,l3 OK!,"
11,20179005948,JOÃO PEDRO DOS SANTOS PATROCINIO,0,0,0,0,JOÃO,",,,"
12,20219041319,JORDANA BEZERRA FRANCA,1,1,1,1,JORDANA,"l1 OK!,l2 OK!,l3 OK!,l4 OK!"
13,20229001200,LAILA TEIXEIRA LOPES,0,1,1,1,LAILA,",l2 OK!,l3 OK!,l4 OK!"
14,20179024317,LEONIDAS PEREIRA DE ABREU,0,0,0,0,LEONIDAS,",,,"
15,20209018344,NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA,1,1,1,1,NIVALDO,"l1 OK!,l2 OK!,l3 OK!,l4 OK!"
16,20229001406,RAFFAEL FERREIRA FERNANDES,1,1,1,1,RAFFAEL,"l1 OK!,l2 OK!,l3 OK!,l4 OK!"
17,20209061200,RODRIGO EDUARDO DE ALENCAR MARQUES,1,0,1,0,RODRIGO,"l1 OK!,,l3 OK!,"
18,20189002378,SAMUEL DA SILVA CRUZ,1,0,1,1,SAMUEL,"l1 OK!,,l3 OK!,l4 OK!"
19,20169040943,SILVESTRE MOURA RODRIGUES,0,0,0,0,SILVESTRE,",,,"
20,20189007795,VIVAL JOSE SEIXAS DE CASTRO FILHO,0,0,0,0,VIVAL,",,,"
21,20229006206,WESLEY DE SOUSA COUTINHO,0,0,1,0,WESLEY,",,l3 OK!,"