<a href="https://colab.research.google.com/github/armandossrecife/teste/blob/main/listas_es2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!wget https://raw.githubusercontent.com/armandossrecife/teste/main/alunos_es2_20232.txt
!wget https://raw.githubusercontent.com/armandossrecife/teste/main/alunos_equipes.txt

--2023-12-08 00:45:50--  https://raw.githubusercontent.com/armandossrecife/teste/main/alunos_es2_20232.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1503 (1.5K) [text/plain]
Saving to: ‘alunos_es2_20232.txt’

alunos_es2_20232.tx 100%[===================>]   1.47K  --.-KB/s    in 0s

2023-12-08 00:45:50 (28.9 MB/s) - ‘alunos_es2_20232.txt’ saved [1503/1503]

--2023-12-08 00:45:50--  https://raw.githubusercontent.com/armandossrecife/teste/main/alunos_equipes.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1754 (1.7K) [text/plain]
Saving to: ‘alunos_equipes.txt’

alunos_equipes.txt  100%[===================>]   1.71K  --.-KB/s    in 0s

2023-12-08 00:45:50 (17.8 MB/s) - ‘alunos_equipes.txt’ saved [1754/1754]

In [8]:
lista_alunos = []
with open('alunos_es2_20232.txt', mode='r') as f_alunos:
  for line in f_alunos:
    line = line.strip()
    aluno_temp = line.split(' ')
    matricula = aluno_temp[0]
    nome = ' '.join(aluno_temp[1:])
    aluno = matricula, nome
    lista_alunos.append(aluno)

In [9]:
lista_equipes = []
dict_equipes = {}
with open('alunos_equipes.txt',mode='r') as f_equipes:
  for line in f_equipes:
    line = line.split(',')
    matricula = line[0]
    nome = line[1]
    equipe = line[2].strip()
    dict_equipes[matricula] = nome, equipe

In [10]:
dict_equipes

{'20219028326': ('ANA CAROLLINE SANTOS SILVA', 'equipe1'),
 '20219017529': ('BENJAMIN SANTOS SILVA', 'equipe1'),
 '20219000719': ('HIRO NAKATU', 'equipe1'),
 '20219022654': ('ITALO BORGES DOS SANTOS', 'equipe1'),
 '20209018344': ('NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA', 'equipe1'),
 '20209012897': ('Landerson Miguel', 'equipe1'),
 '20209050584': ('Ícaro Gabryel de Araujo Silva', 'equipe2'),
 '20209051311': ('Cayo Cesar Lopes Mascarenhas Pires Cardoso', 'equipe2'),
 '20209060375': ('Claudiney Ryan da Silva', 'equipe2'),
 '20209009819': ('Fábio Anderson Carvalho Silva', 'equipe2'),
 '20209061200': ('RODRIGO EDUARDO DE ALENCAR MARQUES', 'equipe2'),
 '20199014050': ('Lucas Sales', 'equipe2'),
 '20219002080': ('João Filipe Batista e Silva', 'equipe3'),
 '20179130383': ('Matheus do Vale Alencar', 'equipe3'),
 '20209068570': ('Neemias Calebe Pereira Freire', 'equipe3'),
 '20189049820': ('Rhuan Moura Oliveira Meireles de Carvalho', 'equipe3'),
 '20219006374': ('Ytallo Gomes Ribeiro Mendes', 'equipe3'),
 '20209003744': ('Francisco Cosme', 'equipe3'),
 '20219001064': ('João Pedro Soares do Monte', 'equipe4'),
 '20219006561': ('Angelus Fayran Lima Rocha', 'equipe4'),
 '20219015767': ('Guilherme Torres Melo', 'equipe4'),
 '20219002885': ('Mateus De Sousa Moura', 'equipe4'),
 '20219001930': ('Marcelo Do Val Brito', 'equipe4'),
 '20209061167': ('Oscar William Nunes de Carvalho', 'equipe5'),
 '20209025803': ('Guilherme Eduardo Almeida Martinelis', 'equipe5'),
 '20219019588': ('Pedro Henrique Sousa de Oliveira', 'equipe5'),
 '20209072189': ('Rayanne Ellen Lopes Figueiredo', 'equipe5'),
 '20189037417': ('Milena Arysa Brito Portela', 'equipe6'),
 '20219011525': ('Ellem Almeida Amorim', 'equipe6'),
 '20219002295': ('Pedro Felipe Ferreira de Abreu', 'equipe6'),
 '20219001260': ('Ryan Ferreira de Sousa', 'equipe6'),
 '20219000129': ('Vinícius Alves de Moura', 'equipe6'),
 '20219000595': ('Luis Felipe Cabral Brito', 'equipe7'),
 '20219007980': ('Luis Gustavo da Silva Sousa', 'equipe7'),
 '20219019630': ('Luiz Henrique Mesquita de Aquino', 'equipe7'),
 '20219010760': ('Ramon Matheus da Silva Fernandes', 'equipe7'),
 '20219012148': ('Victor Hugo de Souza Campos', 'equipe7')}

In [11]:
lista_alunos_es2 = [('20219028326', 'ANA CAROLLINE SANTOS SILVA'),
 ('20219006561', 'ANGELUS FAYRAN LIMA ROCHA'),
 ('20219017529', 'BENJAMIN SANTOS SILVA'),
 ('20209051311', 'CAYO CESAR LOPES MASCARENHAS PIRES CARDOSO'),
 ('20209060375', 'CLAUDINEY RYAN DA SILVA'),
 ('20219011525', 'ELLEM ALMEIDA AMORIM'),
 ('20209009819', 'FABIO ANDERSON CARVALHO SILVA'),
 ('20209003744', 'FRANCISCO COSME MONTEIRO XAVIER'),
 ('20209025803', 'GUILHERME EDUARDO ALMEIDA MARTINELIS'),
 ('20219015767', 'GUILHERME TORRES MELO'),
 ('20219000719', 'HIRO YUMI NAKATU'),
 ('20209050584', 'ICARO GABRYEL DE ARAUJO SILVA'),
 ('20219022654', 'ITALO BORGES DOS SANTOS'),
 ('20219002080', 'JOAO FILIPE BATISTA E SILVA'),
 ('20219001064', 'JOAO PEDRO SOARES DO MONTE'),
 ('20209012897', 'LANDERSON MIGUEL SANTOS COSTA'),
 ('20199014050', 'LUCAS SALES AGUIAR SILVEIRA'),
 ('20219000595', 'LUIS FELIPE CABRAL BRITO'),
 ('20219007980', 'LUIS GUSTAVO DA SILVA SOUSA'),
 ('20219019630', 'LUIZ HENRIQUE MESQUITA DE AQUINO'),
 ('20219001930', 'MARCELO DO VAL BRITO'),
 ('20219002885', 'MATEUS DE SOUSA MOURA'),
 ('20179130383', 'MATHEUS DO VALE ALENCAR'),
 ('20189037417', 'MILENA ARYSA BRITO PORTELA'),
 ('20209068570', 'NEEMIAS CALEBE PEREIRA FREIRE'),
 ('20209018344', 'NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA'),
 ('20209061167', 'OSCAR WILLIAM NUNES DE CARVALHO'),
 ('20219002295', 'PEDRO FELIPE FERREIRA DE ABREU'),
 ('20219019588', 'PEDRO HENRIQUE SOUSA DE OLIVEIRA'),
 ('20219010760', 'RAMON MATHEUS DA SILVA FERNANDES'),
 ('20209072189', 'RAYANNE ELLEN LOPES FIGUEIREDO'),
 ('20189049820', 'RHUAN MOURA OLIVEIRA MEIRELES DE CARVALHO'),
 ('20209061200', 'RODRIGO EDUARDO DE ALENCAR MARQUES'),
 ('20219001260', 'RYAN FERREIRA DE SOUSA'),
 ('20219012148', 'VICTOR HUGO DE SOUZA CAMPOS'),
 ('20219000129', 'VINICIUS ALVES DE MOURA'),
 ('20219006374', 'YTALLO GOMES RIBEIRO MENDES')]

In [12]:
dict_alunos_es2 = {}
for each in lista_alunos_es2:
  dict_alunos_es2[each[0]] = each[1]

In [13]:
lista1_nomes = ['ANA CAROLLINE SANTOS SILVA', 'ANGELUS FAYRAN LIMA ROCHA', 'BENJAMIN SANTOS SILVA', 'CAYO CESAR LOPES MASCARENHAS PIRES CARDOSO', 'CLAUDINEY RYAN DA SILVA', 'ELLEM ALMEIDA AMORIM', 'FABIO ANDERSON CARVALHO SILVA', 'FRANCISCO COSME MONTEIRO XAVIER', 'GUILHERME EDUARDO ALMEIDA MARTINELIS', 'GUILHERME TORRES MELO', 'HIRO YUMI NAKATU', 'ICARO GABRYEL DE ARAUJO SILVA', 'ITALO BORGES DOS SANTOS', 'JOAO FILIPE BATISTA E SILVA', 'LANDERSON MIGUEL SANTOS COSTA', 'LUCAS SALES AGUIAR SILVEIRA', 'LUIS FELIPE CABRAL BRITO', 'LUIS GUSTAVO DA SILVA SOUSA', 'LUIZ HENRIQUE MESQUITA DE AQUINO', 'MARCELO DO VAL BRITO', 'MATHEUS DO VALE ALENCAR', 'MILENA ARYSA BRITO PORTELA', 'NEEMIAS CALEBE PEREIRA FREIRE', 'NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA', 'OSCAR WILLIAM NUNES DE CARVALHO', 'PEDRO FELIPE FERREIRA DE ABREU', 'RAMON MATHEUS DA SILVA FERNANDES', 'RHUAN MOURA OLIVEIRA MEIRELES DE CARVALHO', 'RODRIGO EDUARDO DE ALENCAR MARQUES', 'RYAN FERREIRA DE SOUSA', 'VICTOR HUGO DE SOUZA CAMPOS', 'VINICIUS ALVES DE MOURA', 'YTALLO GOMES RIBEIRO MENDES']

In [14]:
lista2_nomes = ['ANA CAROLLINE SANTOS SILVA', 'ANGELUS FAYRAN LIMA ROCHA', 'BENJAMIN SANTOS SILVA', 'CAYO CESAR LOPES MASCARENHAS PIRES CARDOSO', 'CLAUDINEY RYAN DA SILVA', 'ELLEM ALMEIDA AMORIM', 'FABIO ANDERSON CARVALHO SILVA', 'FRANCISCO COSME MONTEIRO XAVIER', 'GUILHERME EDUARDO ALMEIDA MARTINELIS', 'GUILHERME TORRES MELO', 'HIRO YUMI NAKATU', 'ICARO GABRYEL DE ARAUJO SILVA', 'ITALO BORGES DOS SANTOS', 'JOAO FILIPE BATISTA E SILVA', 'JOAO PEDRO SOARES DO MONTE', 'LANDERSON MIGUEL SANTOS COSTA', 'LUIS FELIPE CABRAL BRITO', 'LUIS GUSTAVO DA SILVA SOUSA', 'LUIZ HENRIQUE MESQUITA DE AQUINO', 'MARCELO DO VAL BRITO', 'MATHEUS DO VALE ALENCAR', 'MILENA ARYSA BRITO PORTELA', 'NEEMIAS CALEBE PEREIRA FREIRE', 'NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA', 'OSCAR WILLIAM NUNES DE CARVALHO', 'PEDRO FELIPE FERREIRA DE ABREU', 'PEDRO HENRIQUE SOUSA DE OLIVEIRA', 'RAMON MATHEUS DA SILVA FERNANDES', 'RAYANNE ELLEN LOPES FIGUEIREDO', 'RHUAN MOURA OLIVEIRA MEIRELES DE CARVALHO', 'RODRIGO EDUARDO DE ALENCAR MARQUES', 'RYAN FERREIRA DE SOUSA', 'VICTOR HUGO DE SOUZA CAMPOS', 'VINICIUS ALVES DE MOURA', 'YTALLO GOMES RIBEIRO MENDES']

In [15]:
lista3_nomes = ['ANA CAROLLINE SANTOS SILVA', 'BENJAMIN SANTOS SILVA', 'CAYO CESAR LOPES MASCARENHAS PIRES CARDOSO', 'CLAUDINEY RYAN DA SILVA', 'ELLEM ALMEIDA AMORIM', 'FABIO ANDERSON CARVALHO SILVA', 'FRANCISCO COSME MONTEIRO XAVIER', 'GUILHERME EDUARDO ALMEIDA MARTINELIS', 'GUILHERME TORRES MELO', 'HIRO YUMI NAKATU', 'ICARO GABRYEL DE ARAUJO SILVA', 'ITALO BORGES DOS SANTOS', 'JOAO FILIPE BATISTA E SILVA', 'JOAO PEDRO SOARES DO MONTE', 'LANDERSON MIGUEL SANTOS COSTA', 'LUIS FELIPE CABRAL BRITO', 'LUIS GUSTAVO DA SILVA SOUSA', 'LUIZ HENRIQUE MESQUITA DE AQUINO', 'MARCELO DO VAL BRITO', 'MATHEUS DO VALE ALENCAR', 'MILENA ARYSA BRITO PORTELA', 'NEEMIAS CALEBE PEREIRA FREIRE', 'NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA', 'OSCAR WILLIAM NUNES DE CARVALHO', 'PEDRO FELIPE FERREIRA DE ABREU', 'PEDRO HENRIQUE SOUSA DE OLIVEIRA', 'RAMON MATHEUS DA SILVA FERNANDES', 'RAYANNE ELLEN LOPES FIGUEIREDO', 'RODRIGO EDUARDO DE ALENCAR MARQUES', 'RYAN FERREIRA DE SOUSA', 'VICTOR HUGO DE SOUZA CAMPOS', 'VINICIUS ALVES DE MOURA', 'YTALLO GOMES RIBEIRO MENDES']

In [16]:
lista_label_matricula, lista_label_nome, lista_label_l1, lista_label_l2, lista_label_l3, lista_label_equipe = list(), list(), list(), list(), list(), list()

In [17]:
for k, v in dict_alunos_es2.items():
  lista_label_matricula.append(k)
  lista_label_nome.append(v)

In [18]:
dict_tutoriais_requisitos = {
    'equipe1': [('tutoriais',4), ('requisitos', 3)],
	'equipe2': [('tutoriais',3.5), ('requisitos',3)],
	'equipe3': [('tutoriais',4), ('requisitos',3)],
	'equipe4': [('tutoriais',3), ('requisitos',3)],
	'equipe5': [('tutoriais',4), ('requisitos', 3)],
	'equipe6': [('tutoriais',4), ('requisitos', 3)],
	'equipe7': [('tutoriais',4), ('requisitos',3)]
}

In [19]:
lista_label_l1, lista_label_l2, lista_label_l3, lista_label_equipe, lista_label_tutoriais, lista_label_requisitos = [], [], [], [], [], []

for k, v in dict_alunos_es2.items():
  if v in lista1_nomes:
    lista_label_l1.append(1)
  else:
    lista_label_l1.append(0)

  if v in lista2_nomes:
    lista_label_l2.append(1)
  else:
    lista_label_l2.append(0)

  if v in lista3_nomes:
    lista_label_l3.append(1)
  else:
    lista_label_l3.append(0)

  my_tuple = dict_equipes[k]
  equipe = my_tuple[1]
  lista_label_equipe.append(equipe)

  dict_tutoriais_requisitos[equipe]
  dados = dict_tutoriais_requisitos[equipe]
  tutoriais = dados[0]
  requisitos = dados[1]

  lista_label_tutoriais.append(tutoriais[1])
  lista_label_requisitos.append(requisitos[1])

In [25]:
dict_alunos_listas = {
    'matricula': lista_label_matricula,
    'nome': lista_label_nome,
    'l1': lista_label_l1,
    'l2': lista_label_l2,
    'l3': lista_label_l3,
    'equipe': lista_label_equipe,
    'tutorial': lista_label_tutoriais,
    'requisitos': lista_label_requisitos
}

In [26]:
import pandas as pd

In [28]:
df_alunos_listas = pd.DataFrame(dict_alunos_listas)
df_alunos_listas['soma_listas'] = df_alunos_listas['l1'] + df_alunos_listas['l2'] + df_alunos_listas['l3']
df_alunos_listas['nota'] = df_alunos_listas['soma_listas'] + df_alunos_listas['requisitos'] + df_alunos_listas['tutorial']
df_alunos_listas

,matricula,nome,l1,l2,l3,equipe,tutorial,requisitos,soma_listas,nota
0,20219028326,ANA CAROLLINE SANTOS SILVA,1,1,1,equipe1,4.0,3,3,10.0
1,20219006561,ANGELUS FAYRAN LIMA ROCHA,1,1,0,equipe4,3.0,3,2,8.0
2,20219017529,BENJAMIN SANTOS SILVA,1,1,1,equipe1,4.0,3,3,10.0
3,20209051311,CAYO CESAR LOPES MASCARENHAS PIRES CARDOSO,1,1,1,equipe2,3.5,3,3,9.5
4,20209060375,CLAUDINEY RYAN DA SILVA,1,1,1,equipe2,3.5,3,3,9.5
5,20219011525,ELLEM ALMEIDA AMORIM,1,1,1,equipe6,4.0,3,3,10.0
6,20209009819,FABIO ANDERSON CARVALHO SILVA,1,1,1,equipe2,3.5,3,3,9.5
7,20209003744,FRANCISCO COSME MONTEIRO XAVIER,1,1,1,equipe3,4.0,3,3,10.0
8,20209025803,GUILHERME EDUARDO ALMEIDA MARTINELIS,1,1,1,equipe5,4.0,3,3,10.0
9,20219015767,GUILHERME TORRES MELO,1,1,1,equipe4,3.0,3,3,9.0
10,20219000719,HIRO YUMI NAKATU,1,1,1,equipe1,4.0,3,3,10.0
11,20209050584,ICARO GABRYEL DE ARAUJO SILVA,1,1,1,equipe2,3.5,3,3,9.5
12,20219022654,ITALO BORGES DOS SANTOS,1,1,1,equipe1,4.0,3,3,10.0
13,20219002080,JOAO FILIPE BATISTA E SILVA,1,1,1,equipe3,4.0,3,3,10.0
14,20219001064,JOAO PEDRO SOARES DO MONTE,0,1,1,equipe4,3.0,3,2,8.0
15,20209012897,LANDERSON MIGUEL SANTOS COSTA,1,1,1,equipe1,4.0,3,3,10.0
16,20199014050,LUCAS SALES AGUIAR SILVEIRA,1,0,0,equipe2,3.5,3,1,7.5
17,20219000595,LUIS FELIPE CABRAL BRITO,1,1,1,equipe7,4.0,3,3,10.0
18,20219007980,LUIS GUSTAVO DA SILVA SOUSA,1,1,1,equipe7,4.0,3,3,10.0
19,20219019630,LUIZ HENRIQUE MESQUITA DE AQUINO,1,1,1,equipe7,4.0,3,3,10.0
20,20219001930,MARCELO DO VAL BRITO,1,1,1,equipe4,3.0,3,3,9.0
21,20219002885,MATEUS DE SOUSA MOURA,0,0,0,equipe4,3.0,3,0,6.0
22,20179130383,MATHEUS DO VALE ALENCAR,1,1,1,equipe3,4.0,3,3,10.0
23,20189037417,MILENA ARYSA BRITO PORTELA,1,1,1,equipe6,4.0,3,3,10.0
24,20209068570,NEEMIAS CALEBE PEREIRA FREIRE,1,1,1,equipe3,4.0,3,3,10.0
25,20209018344,NIVALDO NOGUEIRA PARANAGUA SANTOS E SILVA,1,1,1,equipe1,4.0,3,3,10.0
26,20209061167,OSCAR WILLIAM NUNES DE CARVALHO,1,1,1,equipe5,4.0,3,3,10.0
27,20219002295,PEDRO FELIPE FERREIRA DE ABREU,1,1,1,equipe6,4.0,3,3,10.0
28,20219019588,PEDRO HENRIQUE SOUSA DE OLIVEIRA,0,1,1,equipe5,4.0,3,2,9.0
29,20219010760,RAMON MATHEUS DA SILVA FERNANDES,1,1,1,equipe7,4.0,3,3,10.0
30,20209072189,RAYANNE ELLEN LOPES FIGUEIREDO,0,1,1,equipe5,4.0,3,2,9.0
31,20189049820,RHUAN MOURA OLIVEIRA MEIRELES DE CARVALHO,1,1,0,equipe3,4.0,3,2,9.0
32,20209061200,RODRIGO EDUARDO DE ALENCAR MARQUES,1,1,1,equipe2,3.5,3,3,9.5
33,20219001260,RYAN FERREIRA DE SOUSA,1,1,1,equipe6,4.0,3,3,10.0
34,20219012148,VICTOR HUGO DE SOUZA CAMPOS,1,1,1,equipe7,4.0,3,3,10.0
35,20219000129,VINICIUS ALVES DE MOURA,1,1,1,equipe6,4.0,3,3,10.0
36,20219006374,YTALLO GOMES RIBEIRO MENDES,1,1,1,equipe3,4.0,3,3,10.0

In [31]:
df_nota1 = df_alunos_listas[['matricula', 'soma_listas', 'requisitos', 'tutorial', 'nota']]
df_nota1

      matricula  soma_listas  requisitos  tutorial  nota
0   20219028326            3           3       4.0  10.0
1   20219006561            2           3       3.0   8.0
2   20219017529            3           3       4.0  10.0
3   20209051311            3           3       3.5   9.5
4   20209060375            3           3       3.5   9.5
5   20219011525            3           3       4.0  10.0
6   20209009819            3           3       3.5   9.5
7   20209003744            3           3       4.0  10.0
8   20209025803            3           3       4.0  10.0
9   20219015767            3           3       3.0   9.0
10  20219000719            3           3       4.0  10.0
11  20209050584            3           3       3.5   9.5
12  20219022654            3           3       4.0  10.0
13  20219002080            3           3       4.0  10.0
14  20219001064            2           3       3.0   8.0
15  20209012897            3           3       4.0  10.0
16  20199014050            1           3       3.5   7.5
17  20219000595            3           3       4.0  10.0
18  20219007980            3           3       4.0  10.0
19  20219019630            3           3       4.0  10.0
20  20219001930            3           3       3.0   9.0
21  20219002885            0           3       3.0   6.0
22  20179130383            3           3       4.0  10.0
23  20189037417            3           3       4.0  10.0
24  20209068570            3           3       4.0  10.0
25  20209018344            3           3       4.0  10.0
26  20209061167            3           3       4.0  10.0
27  20219002295            3           3       4.0  10.0
28  20219019588            2           3       4.0   9.0
29  20219010760            3           3       4.0  10.0
30  20209072189            2           3       4.0   9.0
31  20189049820            2           3       4.0   9.0
32  20209061200            3           3       3.5   9.5
33  20219001260            3           3       4.0  10.0
34  20219012148            3           3       4.0  10.0
35  20219000129            3           3       4.0  10.0
36  20219006374            3           3       4.0  10.0

In [32]:
df_nota1.to_excel('es2nota1.xlsx', index=False)