<a href="https://colab.research.google.com/github/armandossrecife/teste/blob/main/lp_sabtina1_20242_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Lista de alunos matriculados

In [1]:
# 1. Lista de alunos matriculados
!wget https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/alunos_lp_20242.csv

--2024-10-22 13:06:59--  https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/alunos_lp_20242.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1319 (1.3K) [text/plain]
Saving to: ‘alunos_lp_20242.csv’

alunos_lp_20242.csv 100%[===================>]   1.29K  --.-KB/s    in 0s

2024-10-22 13:06:59 (51.6 MB/s) - ‘alunos_lp_20242.csv’ saved [1319/1319]

In [9]:
def limpa_nomes_alunos(lista_nomes_alunos):
  lista_nomes_alunos_limpos = []
  for each in lista_nomes_alunos:
    each = each.replace("\t", "")
    lista_nomes_alunos_limpos.append(each)

  return lista_nomes_alunos_limpos

def gera_lista_respostas(arquivo):
  with open(arquivo) as f_lista:
    lista_alunos = f_lista.read().splitlines()
  return lista_alunos

def gera_dicionario_alunos_lista(dicionario_alunos, lista_alunos_lista):
  dicionario_alunos_lista = {}

  for matricula, nome in dicionario_alunos.items():
    if nome in lista_alunos_lista:
      dicionario_alunos_lista[matricula] = nome

  return dicionario_alunos_lista

def checa_alunos_fezeram_lista(df_alunos, lista_alunos_lista):
  lista1_respostas = []
  for each in lista_alunos_lista:
    if each in df_alunos.nome.tolist():
      print(f"Aluno {each} fez a lista")
      lista1_respostas.append(1)
    else:
      print(f"Aluno {each} não fez a lista")
      lista1_respostas.append(0)

In [15]:
def converte_dicionario_para_dataframe(dicionario):
  df = pd.DataFrame(list(dicionario.items()), columns=['matricula', 'nome'])
  return df

In [4]:
import pandas as pd

df_alunos_20242 = pd.read_csv('alunos_lp_20242.csv')
df_alunos_20242.head(5)

     matricula                                        nome
0  20249023385  ANTONIO CARLOS DE SOUSA COELHO DAMASCENO\t
1  20249021433              ANTONIO INACIO DA SILVA NETO\t
2  20249012229            ARTHUR MAGNO RODRIGUES SAMPAIO\t
3  20249021818                     CAUA MARTINS DA SILVA\t
4  20239035515                     DAVI SOARES DE MACEDO\t

In [7]:
lista_nomes_limpos = limpa_nomes_alunos(df_alunos_20242.nome.tolist())
print(lista_nomes_limpos)

['ANTONIO CARLOS DE SOUSA COELHO DAMASCENO', 'ANTONIO INACIO DA SILVA NETO', 'ARTHUR MAGNO RODRIGUES SAMPAIO', 'CAUA MARTINS DA SILVA', 'DAVI SOARES DE MACEDO', 'DAVI SOUSA SOARES', 'DIEGO VINICIOS MASCARENHA LIMA', 'DIELSON DE MENDONCA SANTOS', 'FELIPE GABRIEL SOARES RODRIGUES', 'GABRIEL ARAUJO ROCHA', 'HELON SANDES BARROS', 'ITALO MARLON DE SOUSA ALVES', 'JARDENIA MILLENA DE SOUSA ROSA', 'JOAO GABRIEL MIRANDA QUEIROZ', 'JOAO MANOEL COSTA MENEZES', 'JOAO MARCELO BARROS CARDOSO VENTURA', 'JOAO PEDRO SALEH DE SOUSA', 'KAUAN FRANCISCO SANTOS SARAIVA', 'LUANDERSON DAVI GONCALVES TORRES', 'LUANDERSON OLIVEIRA DE CARVALHO', 'LUCAS VILARINHO CARVALHO MARTINS CAMARCO', 'MARCOS VINICIUS DUARTE SOUSA', 'MARIA EDUARDA FARIAS GOMES', 'MATEUS RODRIGUES DE SOUSA BORJA', 'MATHEUS CARNEIRO AGUIAR', 'NORBERTO MELO DE CARVALHO FILHO', 'RAIMUNDO NONATO DA SILVA SA SOBRINHO', 'SAMARA FEITOSA DE SOUSA', 'TIAGO GABRIEL COSTA SAMPAIO', 'VICTOR KAUAN DA SILVA MIRANDA', 'WELTER XIMENES CANTANHEDE FILHO']

# Resolução das listas

In [8]:
!wget https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/alunos_lista1_20242.txt
!wget https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/alunos_lista2_20242.txt
!wget https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/alunos_lista3_20242.txt
!wget https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/alunos_lista4_20242.txt

--2024-10-22 13:10:24--  https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/alunos_lista1_20242.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 860 [text/plain]
Saving to: ‘alunos_lista1_20242.txt’

alunos_lista1_20242 100%[===================>]     860  --.-KB/s    in 0s

2024-10-22 13:10:24 (32.8 MB/s) - ‘alunos_lista1_20242.txt’ saved [860/860]

--2024-10-22 13:10:24--  https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/alunos_lista2_20242.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 902 [text/plain]
Saving to: ‘alunos_lista2_20242.txt’

alunos_lista2_20242 100%[===================>]     902  --.-KB/s    in 0s

2024-10-22 13:10:24 (43.9 MB/s) - ‘alunos_lista2_20242.txt’ saved [902/902]

--2024-10-22 13:10:25--  https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/alunos_lista3_20242.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 749 [text/plain]
Saving to: ‘alunos_lista3_20242.txt’

alunos_lista3_20242 100%[===================>]     749  --.-KB/s    in 0s

2024-10-22 13:10:25 (23.4 MB/s) - ‘alunos_lista3_20242.txt’ saved [749/749]

--2024-10-22 13:10:25--  https://raw.githubusercontent.com/armandossrecife/teste/refs/heads/main/alunos_lista4_20242.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 687 [text/plain]
Saving to: ‘alunos_lista4_20242.txt’

alunos_lista4_20242 100%[===================>]     687  --.-KB/s    in 0s

2024-10-22 13:10:25 (38.3 MB/s) - ‘alunos_lista4_20242.txt’ saved [687/687]

In [11]:
lista_alunos_matriculados = df_alunos_20242.matricula.tolist()
dicionario_alunos = {}
for matricula, nome in zip(lista_alunos_matriculados, lista_nomes_limpos):
  dicionario_alunos[matricula] = nome

dicionario_alunos

{20249023385: 'ANTONIO CARLOS DE SOUSA COELHO DAMASCENO',
 20249021433: 'ANTONIO INACIO DA SILVA NETO',
 20249012229: 'ARTHUR MAGNO RODRIGUES SAMPAIO',
 20249021818: 'CAUA MARTINS DA SILVA',
 20239035515: 'DAVI SOARES DE MACEDO',
 20249022000: 'DAVI SOUSA SOARES',
 20249018456: 'DIEGO VINICIOS MASCARENHA LIMA',
 20249021264: 'DIELSON DE MENDONCA SANTOS',
 20249020884: 'FELIPE GABRIEL SOARES RODRIGUES',
 20249022010: 'GABRIEL ARAUJO ROCHA',
 20229052844: 'HELON SANDES BARROS',
 20249013226: 'ITALO MARLON DE SOUSA ALVES',
 20249011704: 'JARDENIA MILLENA DE SOUSA ROSA',
 20239057110: 'JOAO GABRIEL MIRANDA QUEIROZ',
 20249023278: 'JOAO MANOEL COSTA MENEZES',
 20249021961: 'JOAO MARCELO BARROS CARDOSO VENTURA',
 20249012194: 'JOAO PEDRO SALEH DE SOUSA',
 20249021970: 'KAUAN FRANCISCO SANTOS SARAIVA',
 20249020857: 'LUANDERSON DAVI GONCALVES TORRES',
 20249012050: 'LUANDERSON OLIVEIRA DE CARVALHO',
 20249011769: 'LUCAS VILARINHO CARVALHO MARTINS CAMARCO',
 20249021139: 'MARCOS VINICIUS DUARTE SOUSA',
 20239049987: 'MARIA EDUARDA FARIAS GOMES',
 20239052276: 'MATEUS RODRIGUES DE SOUSA BORJA',
 20249012336: 'MATHEUS CARNEIRO AGUIAR',
 20219042129: 'NORBERTO MELO DE CARVALHO FILHO',
 20249021765: 'RAIMUNDO NONATO DA SILVA SA SOBRINHO',
 20249011553: 'SAMARA FEITOSA DE SOUSA',
 20239046116: 'TIAGO GABRIEL COSTA SAMPAIO',
 20249021999: 'VICTOR KAUAN DA SILVA MIRANDA',
 20249023170: 'WELTER XIMENES CANTANHEDE FILHO'}

In [12]:
lista_alunos_lista1_20242= gera_lista_respostas('alunos_lista1_20242.txt')
lista_alunos_lista2_20242 = gera_lista_respostas('alunos_lista2_20242.txt')
lista_alunos_lista3_20242 = gera_lista_respostas('alunos_lista3_20242.txt')
lista_alunos_lista4_20242 = gera_lista_respostas('alunos_lista4_20242.txt')

In [13]:
dicionario_lista1 = gera_dicionario_alunos_lista(dicionario_alunos, lista_alunos_lista1_20242)
dicionario_lista2 = gera_dicionario_alunos_lista(dicionario_alunos, lista_alunos_lista2_20242)
dicionario_lista3 = gera_dicionario_alunos_lista(dicionario_alunos, lista_alunos_lista3_20242)
dicionario_lista4 = gera_dicionario_alunos_lista(dicionario_alunos, lista_alunos_lista4_20242)

In [16]:
df_alunos_x = converte_dicionario_para_dataframe(dicionario_alunos)
df_lista1 = converte_dicionario_para_dataframe(dicionario_lista1)
df_lista2 = converte_dicionario_para_dataframe(dicionario_lista2)
df_lista3 = converte_dicionario_para_dataframe(dicionario_lista3)
df_lista4 = converte_dicionario_para_dataframe(dicionario_lista4)

# Checa os alunos que fizeram as listas

In [18]:
def checa_alunos_fezeram_lista(df_alunos, lista_alunos_lista):
  lista1_respostas = []
  for each in df_alunos.nome.tolist():
    if each in lista_alunos_lista:
      lista1_respostas.append(1)
    else:
      lista1_respostas.append(0)
  return lista1_respostas

In [19]:
lista1_respostas = checa_alunos_fezeram_lista(df_alunos_x, lista_alunos_lista1_20242)
lista2_respostas = checa_alunos_fezeram_lista(df_alunos_x, lista_alunos_lista2_20242)
lista3_respostas = checa_alunos_fezeram_lista(df_alunos_x, lista_alunos_lista3_20242)
lista4_respostas = checa_alunos_fezeram_lista(df_alunos_x, lista_alunos_lista4_20242)

In [20]:
df_alunos_respostas = df_alunos_x.copy()
df_alunos_respostas['lista1'] = lista1_respostas
df_alunos_respostas['lista2'] = lista2_respostas
df_alunos_respostas['lista3'] = lista3_respostas
df_alunos_respostas['lista4'] = lista4_respostas

In [21]:
df_alunos_respostas

,matricula,nome,lista1,lista2,lista3,lista4
0,20249023385,ANTONIO CARLOS DE SOUSA COELHO DAMASCENO,0,1,1,1
1,20249021433,ANTONIO INACIO DA SILVA NETO,1,1,1,1
2,20249012229,ARTHUR MAGNO RODRIGUES SAMPAIO,1,1,1,1
3,20249021818,CAUA MARTINS DA SILVA,1,1,1,1
4,20239035515,DAVI SOARES DE MACEDO,1,1,1,1
5,20249022000,DAVI SOUSA SOARES,1,1,1,1
6,20249018456,DIEGO VINICIOS MASCARENHA LIMA,1,1,1,1
7,20249021264,DIELSON DE MENDONCA SANTOS,1,1,1,1
8,20249020884,FELIPE GABRIEL SOARES RODRIGUES,1,1,1,1
9,20249022010,GABRIEL ARAUJO ROCHA,1,1,1,1
10,20229052844,HELON SANDES BARROS,1,1,1,1
11,20249013226,ITALO MARLON DE SOUSA ALVES,1,1,1,1
12,20249011704,JARDENIA MILLENA DE SOUSA ROSA,1,1,1,0
13,20239057110,JOAO GABRIEL MIRANDA QUEIROZ,1,1,0,1
14,20249023278,JOAO MANOEL COSTA MENEZES,1,1,1,0
15,20249021961,JOAO MARCELO BARROS CARDOSO VENTURA,1,1,1,1
16,20249012194,JOAO PEDRO SALEH DE SOUSA,1,1,1,1
17,20249021970,KAUAN FRANCISCO SANTOS SARAIVA,1,1,0,0
18,20249020857,LUANDERSON DAVI GONCALVES TORRES,1,1,1,1
19,20249012050,LUANDERSON OLIVEIRA DE CARVALHO,1,1,1,1
20,20249011769,LUCAS VILARINHO CARVALHO MARTINS CAMARCO,1,1,1,1
21,20249021139,MARCOS VINICIUS DUARTE SOUSA,1,1,1,0
22,20239049987,MARIA EDUARDA FARIAS GOMES,1,1,0,1
23,20239052276,MATEUS RODRIGUES DE SOUSA BORJA,1,1,1,1
24,20249012336,MATHEUS CARNEIRO AGUIAR,1,1,1,1
25,20219042129,NORBERTO MELO DE CARVALHO FILHO,1,1,1,1
26,20249021765,RAIMUNDO NONATO DA SILVA SA SOBRINHO,1,1,0,0
27,20249011553,SAMARA FEITOSA DE SOUSA,1,1,1,1
28,20239046116,TIAGO GABRIEL COSTA SAMPAIO,1,1,0,0
29,20249021999,VICTOR KAUAN DA SILVA MIRANDA,1,1,1,1
30,20249023170,WELTER XIMENES CANTANHEDE FILHO,1,0,1,0

In [22]:
df_alunos_respostas.to_excel('lista_prova1_alunos_respostas.xlsx')