<a href="https://colab.research.google.com/github/armandossrecife/teste/blob/main/n1n2_pe20251.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Versão Comum

In [ ]:
import pandas as pd

## 1a. Avaliação

In [ ]:
df_l1 = pd.read_csv('av1/lista1.csv')
df_l2 = pd.read_csv('av1/lista2.csv')
df_l3 = pd.read_csv('av1/lista3.csv')
df_l4 = pd.read_csv('av1/lista4.csv')

In [ ]:
df_alunos = pd.read_csv('alunos_pe_20251.csv')

In [ ]:
# prompt: No dataframe df_alunos altere a coluna NOME para Nome

df_alunos = df_alunos.rename(columns={'NOME': 'Nome'})
df_alunos

      MATRICULA                                   Nome
0   20249053885               AECIO FLORINDO DE ARAUJO
1   20249035027              ALICE MARIA CASTRO FERRAZ
2   20249044966             ANA CAROLINA LIMA DE SOUSA
3   20249046405                   BRUNA COSTA DA SILVA
4   20189026600        BRUNO DOS SANTOS BARBOSA DANTAS
5   20249049757               EZEQUIAS DA SILVA SANTOS
6   20249039545                     FELIPE SILVA ROCHA
7   20249045293  FRANCISCO VITORIO DA SILVA DE ANANIAS
8   20249035626            GABRIEL DE OLIVEIRA BARBOSA
9   20249046343                   GABRIEL MACEDO LOPES
10  20249040831               GIOVANNY MENDES DE BRITO
11  20249028443           GUILHERME ARTHUR MATOS SALES
12  20249010019                 ILDBERG SILVA DE SOUSA
13  20249034988       JOSE EDVAR NUNES DE MOURA JUNIOR
14  20249009250                JULIO CESAR SILVA SOUSA
15  20249049766             JULIO GABRIEL MELO BACELAR
16  20249010743                KAIO VICTOR SILVA SOUSA
17  20249045177              KLEBER DOS SANTOS PEREIRA
18  20249046245      LOURIVAL FERNANDES DE ARAUJO NETO
19  20249016881              LUCAS DOS SANTOS DE SALES
20  20249036561            LUIS SILVIO MOREIRA ALMEIDA
21  20249053437           LUIZ RODRIGUES DA SILVA NETO
22  20249041777                 MARCELO OLIVEIRA SILVA
23  20249033120             MARCUS ELIAS GOMES BEZERRA
24  20249051002       MATEUS DE MOURA FERREIRA MOREIRA
25  20249011150        MATHEUS SARAIVA CIPRIANO DANTAS
26  20249011349        PAULO GUILHERME ARAUJO DA SILVA
27  20249048651     PAULO VENICIOS DA SILVA NASCIMENTO
28  20249046441              RAMON NICOLAS SILVA CEZAR
29  20249034075     RIAN FILIPE ARAUJO SOARES DE SOUSA
30  20249035573  VICTOR GABRIEL DE JESUS MATIAS VIEIRA

In [ ]:
df_alunos['l1'] = 0
df_alunos['l2'] = 0
df_alunos['l3'] = 0
df_alunos['l4'] = 0

In [ ]:
l1 = df_l1.Nome.to_list()
l2 = df_l2.Nome.to_list()
l3 = df_l3.Nome.to_list()
l4 = df_l4.Nome.to_list()

In [ ]:
# prompt: Crie um script que caso o nome do aluno apareça na lista 1 l1, altere o valor de l1 para 1 no dataframe df_alunos, faça isso para todos os alunos na lista 2 l2, lista 3 l3 e lista 4 l4.

# Iterate through the DataFrame and update the 'l1' column
for index, row in df_alunos.iterrows():
    if row['Nome'] in l1:
        df_alunos.loc[index, 'l1'] = 1
    if row['Nome'] in l2:
        df_alunos.loc[index, 'l2'] = 1
    if row['Nome'] in l3:
        df_alunos.loc[index, 'l3'] = 1
    if row['Nome'] in l4:
        df_alunos.loc[index, 'l4'] = 1
# Print the updated DataFrame (optional)
print(df_alunos.head())

     MATRICULA                             Nome  l1  l2  l3  l4
0  20249053885         AECIO FLORINDO DE ARAUJO   1   1   1   1
1  20249035027        ALICE MARIA CASTRO FERRAZ   0   0   1   1
2  20249044966       ANA CAROLINA LIMA DE SOUSA   1   1   0   0
3  20249046405             BRUNA COSTA DA SILVA   1   1   1   1
4  20189026600  BRUNO DOS SANTOS BARBOSA DANTAS   1   0   0   0

In [ ]:
df_alunos

      MATRICULA                                   Nome  l1  l2  l3  l4
0   20249053885               AECIO FLORINDO DE ARAUJO   1   1   1   1
1   20249035027              ALICE MARIA CASTRO FERRAZ   0   0   1   1
2   20249044966             ANA CAROLINA LIMA DE SOUSA   1   1   0   0
3   20249046405                   BRUNA COSTA DA SILVA   1   1   1   1
4   20189026600        BRUNO DOS SANTOS BARBOSA DANTAS   1   0   0   0
5   20249049757               EZEQUIAS DA SILVA SANTOS   1   1   1   1
6   20249039545                     FELIPE SILVA ROCHA   1   0   0   1
7   20249045293  FRANCISCO VITORIO DA SILVA DE ANANIAS   1   1   1   1
8   20249035626            GABRIEL DE OLIVEIRA BARBOSA   1   1   1   1
9   20249046343                   GABRIEL MACEDO LOPES   1   1   1   1
10  20249040831               GIOVANNY MENDES DE BRITO   1   1   0   1
11  20249028443           GUILHERME ARTHUR MATOS SALES   0   1   1   0
12  20249010019                 ILDBERG SILVA DE SOUSA   1   1   1   1
13  20249034988       JOSE EDVAR NUNES DE MOURA JUNIOR   1   0   1   1
14  20249009250                JULIO CESAR SILVA SOUSA   1   1   1   0
15  20249049766             JULIO GABRIEL MELO BACELAR   1   1   1   1
16  20249010743                KAIO VICTOR SILVA SOUSA   0   0   1   1
17  20249045177              KLEBER DOS SANTOS PEREIRA   1   0   1   0
18  20249046245      LOURIVAL FERNANDES DE ARAUJO NETO   1   1   1   1
19  20249016881              LUCAS DOS SANTOS DE SALES   1   1   0   1
20  20249036561            LUIS SILVIO MOREIRA ALMEIDA   0   1   1   1
21  20249053437           LUIZ RODRIGUES DA SILVA NETO   1   1   1   1
22  20249041777                 MARCELO OLIVEIRA SILVA   1   1   1   1
23  20249033120             MARCUS ELIAS GOMES BEZERRA   1   1   1   1
24  20249051002       MATEUS DE MOURA FERREIRA MOREIRA   1   1   1   1
25  20249011150        MATHEUS SARAIVA CIPRIANO DANTAS   0   1   1   1
26  20249011349        PAULO GUILHERME ARAUJO DA SILVA   1   1   1   1
27  20249048651     PAULO VENICIOS DA SILVA NASCIMENTO   1   1   1   1
28  20249046441              RAMON NICOLAS SILVA CEZAR   0   1   1   1
29  20249034075     RIAN FILIPE ARAUJO SOARES DE SOUSA   1   1   1   1
30  20249035573  VICTOR GABRIEL DE JESUS MATIAS VIEIRA   1   1   0   0

In [ ]:
# prompt: Para o dataframe df_alunos, substitua NaN por 0 (Zero)

df_alunos = df_alunos.fillna(0)
print(df_alunos.head())

     MATRICULA                             Nome  l1  l2  l3  l4
0  20249053885         AECIO FLORINDO DE ARAUJO   1   1   1   1
1  20249035027        ALICE MARIA CASTRO FERRAZ   0   0   1   1
2  20249044966       ANA CAROLINA LIMA DE SOUSA   1   1   0   0
3  20249046405             BRUNA COSTA DA SILVA   1   1   1   1
4  20189026600  BRUNO DOS SANTOS BARBOSA DANTAS   1   0   0   0

In [ ]:
df_alunos

      MATRICULA                                   Nome  l1  l2  l3  l4
0   20249053885               AECIO FLORINDO DE ARAUJO   1   1   1   1
1   20249035027              ALICE MARIA CASTRO FERRAZ   0   0   1   1
2   20249044966             ANA CAROLINA LIMA DE SOUSA   1   1   0   0
3   20249046405                   BRUNA COSTA DA SILVA   1   1   1   1
4   20189026600        BRUNO DOS SANTOS BARBOSA DANTAS   1   0   0   0
5   20249049757               EZEQUIAS DA SILVA SANTOS   1   1   1   1
6   20249039545                     FELIPE SILVA ROCHA   1   0   0   1
7   20249045293  FRANCISCO VITORIO DA SILVA DE ANANIAS   1   1   1   1
8   20249035626            GABRIEL DE OLIVEIRA BARBOSA   1   1   1   1
9   20249046343                   GABRIEL MACEDO LOPES   1   1   1   1
10  20249040831               GIOVANNY MENDES DE BRITO   1   1   0   1
11  20249028443           GUILHERME ARTHUR MATOS SALES   0   1   1   0
12  20249010019                 ILDBERG SILVA DE SOUSA   1   1   1   1
13  20249034988       JOSE EDVAR NUNES DE MOURA JUNIOR   1   0   1   1
14  20249009250                JULIO CESAR SILVA SOUSA   1   1   1   0
15  20249049766             JULIO GABRIEL MELO BACELAR   1   1   1   1
16  20249010743                KAIO VICTOR SILVA SOUSA   0   0   1   1
17  20249045177              KLEBER DOS SANTOS PEREIRA   1   0   1   0
18  20249046245      LOURIVAL FERNANDES DE ARAUJO NETO   1   1   1   1
19  20249016881              LUCAS DOS SANTOS DE SALES   1   1   0   1
20  20249036561            LUIS SILVIO MOREIRA ALMEIDA   0   1   1   1
21  20249053437           LUIZ RODRIGUES DA SILVA NETO   1   1   1   1
22  20249041777                 MARCELO OLIVEIRA SILVA   1   1   1   1
23  20249033120             MARCUS ELIAS GOMES BEZERRA   1   1   1   1
24  20249051002       MATEUS DE MOURA FERREIRA MOREIRA   1   1   1   1
25  20249011150        MATHEUS SARAIVA CIPRIANO DANTAS   0   1   1   1
26  20249011349        PAULO GUILHERME ARAUJO DA SILVA   1   1   1   1
27  20249048651     PAULO VENICIOS DA SILVA NASCIMENTO   1   1   1   1
28  20249046441              RAMON NICOLAS SILVA CEZAR   0   1   1   1
29  20249034075     RIAN FILIPE ARAUJO SOARES DE SOUSA   1   1   1   1
30  20249035573  VICTOR GABRIEL DE JESUS MATIAS VIEIRA   1   1   0   0

In [ ]:
df_alunos['av1'] = df_alunos['l1'] + df_alunos['l2'] + df_alunos['l3'] + df_alunos['l4']
df_alunos

      MATRICULA                                   Nome  l1  l2  l3  l4  av1
0   20249053885               AECIO FLORINDO DE ARAUJO   1   1   1   1    4
1   20249035027              ALICE MARIA CASTRO FERRAZ   0   0   1   1    2
2   20249044966             ANA CAROLINA LIMA DE SOUSA   1   1   0   0    2
3   20249046405                   BRUNA COSTA DA SILVA   1   1   1   1    4
4   20189026600        BRUNO DOS SANTOS BARBOSA DANTAS   1   0   0   0    1
5   20249049757               EZEQUIAS DA SILVA SANTOS   1   1   1   1    4
6   20249039545                     FELIPE SILVA ROCHA   1   0   0   1    2
7   20249045293  FRANCISCO VITORIO DA SILVA DE ANANIAS   1   1   1   1    4
8   20249035626            GABRIEL DE OLIVEIRA BARBOSA   1   1   1   1    4
9   20249046343                   GABRIEL MACEDO LOPES   1   1   1   1    4
10  20249040831               GIOVANNY MENDES DE BRITO   1   1   0   1    3
11  20249028443           GUILHERME ARTHUR MATOS SALES   0   1   1   0    2
12  20249010019                 ILDBERG SILVA DE SOUSA   1   1   1   1    4
13  20249034988       JOSE EDVAR NUNES DE MOURA JUNIOR   1   0   1   1    3
14  20249009250                JULIO CESAR SILVA SOUSA   1   1   1   0    3
15  20249049766             JULIO GABRIEL MELO BACELAR   1   1   1   1    4
16  20249010743                KAIO VICTOR SILVA SOUSA   0   0   1   1    2
17  20249045177              KLEBER DOS SANTOS PEREIRA   1   0   1   0    2
18  20249046245      LOURIVAL FERNANDES DE ARAUJO NETO   1   1   1   1    4
19  20249016881              LUCAS DOS SANTOS DE SALES   1   1   0   1    3
20  20249036561            LUIS SILVIO MOREIRA ALMEIDA   0   1   1   1    3
21  20249053437           LUIZ RODRIGUES DA SILVA NETO   1   1   1   1    4
22  20249041777                 MARCELO OLIVEIRA SILVA   1   1   1   1    4
23  20249033120             MARCUS ELIAS GOMES BEZERRA   1   1   1   1    4
24  20249051002       MATEUS DE MOURA FERREIRA MOREIRA   1   1   1   1    4
25  20249011150        MATHEUS SARAIVA CIPRIANO DANTAS   0   1   1   1    3
26  20249011349        PAULO GUILHERME ARAUJO DA SILVA   1   1   1   1    4
27  20249048651     PAULO VENICIOS DA SILVA NASCIMENTO   1   1   1   1    4
28  20249046441              RAMON NICOLAS SILVA CEZAR   0   1   1   1    3
29  20249034075     RIAN FILIPE ARAUJO SOARES DE SOUSA   1   1   1   1    4
30  20249035573  VICTOR GABRIEL DE JESUS MATIAS VIEIRA   1   1   0   0    2

In [ ]:
df_alunos['n1'] = df_alunos['av1']*2.5
df_alunos

,MATRICULA,Nome,l1,l2,l3,l4,av1,n1
0,20249053885,AECIO FLORINDO DE ARAUJO,1,1,1,1,4,10.0
1,20249035027,ALICE MARIA CASTRO FERRAZ,0,0,1,1,2,5.0
2,20249044966,ANA CAROLINA LIMA DE SOUSA,1,1,0,0,2,5.0
3,20249046405,BRUNA COSTA DA SILVA,1,1,1,1,4,10.0
4,20189026600,BRUNO DOS SANTOS BARBOSA DANTAS,1,0,0,0,1,2.5
5,20249049757,EZEQUIAS DA SILVA SANTOS,1,1,1,1,4,10.0
6,20249039545,FELIPE SILVA ROCHA,1,0,0,1,2,5.0
7,20249045293,FRANCISCO VITORIO DA SILVA DE ANANIAS,1,1,1,1,4,10.0
8,20249035626,GABRIEL DE OLIVEIRA BARBOSA,1,1,1,1,4,10.0
9,20249046343,GABRIEL MACEDO LOPES,1,1,1,1,4,10.0
10,20249040831,GIOVANNY MENDES DE BRITO,1,1,0,1,3,7.5
11,20249028443,GUILHERME ARTHUR MATOS SALES,0,1,1,0,2,5.0
12,20249010019,ILDBERG SILVA DE SOUSA,1,1,1,1,4,10.0
13,20249034988,JOSE EDVAR NUNES DE MOURA JUNIOR,1,0,1,1,3,7.5
14,20249009250,JULIO CESAR SILVA SOUSA,1,1,1,0,3,7.5
15,20249049766,JULIO GABRIEL MELO BACELAR,1,1,1,1,4,10.0
16,20249010743,KAIO VICTOR SILVA SOUSA,0,0,1,1,2,5.0
17,20249045177,KLEBER DOS SANTOS PEREIRA,1,0,1,0,2,5.0
18,20249046245,LOURIVAL FERNANDES DE ARAUJO NETO,1,1,1,1,4,10.0
19,20249016881,LUCAS DOS SANTOS DE SALES,1,1,0,1,3,7.5
20,20249036561,LUIS SILVIO MOREIRA ALMEIDA,0,1,1,1,3,7.5
21,20249053437,LUIZ RODRIGUES DA SILVA NETO,1,1,1,1,4,10.0
22,20249041777,MARCELO OLIVEIRA SILVA,1,1,1,1,4,10.0
23,20249033120,MARCUS ELIAS GOMES BEZERRA,1,1,1,1,4,10.0
24,20249051002,MATEUS DE MOURA FERREIRA MOREIRA,1,1,1,1,4,10.0
25,20249011150,MATHEUS SARAIVA CIPRIANO DANTAS,0,1,1,1,3,7.5
26,20249011349,PAULO GUILHERME ARAUJO DA SILVA,1,1,1,1,4,10.0
27,20249048651,PAULO VENICIOS DA SILVA NASCIMENTO,1,1,1,1,4,10.0
28,20249046441,RAMON NICOLAS SILVA CEZAR,0,1,1,1,3,7.5
29,20249034075,RIAN FILIPE ARAUJO SOARES DE SOUSA,1,1,1,1,4,10.0
30,20249035573,VICTOR GABRIEL DE JESUS MATIAS VIEIRA,1,1,0,0,2,5.0

In [ ]:
df_alunos.to_excel('av1.xlsx')

## 2a Avaliação

In [ ]:
# Ler as 4 listas de exercicios
df_l1 = pd.read_csv('av2/lista1.csv')
df_l2 = pd.read_csv('av2/lista2.csv')
df_l3 = pd.read_csv('av2/lista3.csv')
df_l4 = pd.read_csv('av2/lista4.csv')

In [ ]:
# Ler o arquivo de lista de presenca
df_alunos = pd.read_csv('alunos_pe_20251.csv')

In [ ]:
# Altera o nome da coluna
df_alunos = df_alunos.rename(columns={'NOME': 'Nome'})
df_alunos

      MATRICULA                                   Nome
0   20249053885               AECIO FLORINDO DE ARAUJO
1   20249035027              ALICE MARIA CASTRO FERRAZ
2   20249044966             ANA CAROLINA LIMA DE SOUSA
3   20249046405                   BRUNA COSTA DA SILVA
4   20189026600        BRUNO DOS SANTOS BARBOSA DANTAS
5   20249049757               EZEQUIAS DA SILVA SANTOS
6   20249039545                     FELIPE SILVA ROCHA
7   20249045293  FRANCISCO VITORIO DA SILVA DE ANANIAS
8   20249035626            GABRIEL DE OLIVEIRA BARBOSA
9   20249046343                   GABRIEL MACEDO LOPES
10  20249040831               GIOVANNY MENDES DE BRITO
11  20249028443           GUILHERME ARTHUR MATOS SALES
12  20249010019                 ILDBERG SILVA DE SOUSA
13  20249034988       JOSE EDVAR NUNES DE MOURA JUNIOR
14  20249009250                JULIO CESAR SILVA SOUSA
15  20249049766             JULIO GABRIEL MELO BACELAR
16  20249010743                KAIO VICTOR SILVA SOUSA
17  20249045177              KLEBER DOS SANTOS PEREIRA
18  20249046245      LOURIVAL FERNANDES DE ARAUJO NETO
19  20249016881              LUCAS DOS SANTOS DE SALES
20  20249036561            LUIS SILVIO MOREIRA ALMEIDA
21  20249053437           LUIZ RODRIGUES DA SILVA NETO
22  20249041777                 MARCELO OLIVEIRA SILVA
23  20249033120             MARCUS ELIAS GOMES BEZERRA
24  20249051002       MATEUS DE MOURA FERREIRA MOREIRA
25  20249011150        MATHEUS SARAIVA CIPRIANO DANTAS
26  20249011349        PAULO GUILHERME ARAUJO DA SILVA
27  20249048651     PAULO VENICIOS DA SILVA NASCIMENTO
28  20249046441              RAMON NICOLAS SILVA CEZAR
29  20249034075     RIAN FILIPE ARAUJO SOARES DE SOUSA
30  20249035573  VICTOR GABRIEL DE JESUS MATIAS VIEIRA

In [ ]:
# Cria as colunas de listas
df_alunos['l1'] = 0
df_alunos['l2'] = 0
df_alunos['l3'] = 0
df_alunos['l4'] = 0

# Cria as listas para cada coluna
l1 = df_l1.Nome.to_list()
l2 = df_l2.Nome.to_list()
l3 = df_l3.Nome.to_list()
l4 = df_l4.Nome.to_list()

# Iterate through the DataFrame and update the 'l1' column
for index, row in df_alunos.iterrows():
    if row['Nome'] in l1:
        df_alunos.loc[index, 'l1'] = 1
    if row['Nome'] in l2:
        df_alunos.loc[index, 'l2'] = 1
    if row['Nome'] in l3:
        df_alunos.loc[index, 'l3'] = 1
    if row['Nome'] in l4:
        df_alunos.loc[index, 'l4'] = 1

# Atribui zero para NaN
df_alunos = df_alunos.fillna(0)

In [ ]:
# Cria a coluna av2
df_alunos['av2'] = df_alunos['l1'] + df_alunos['l2'] + df_alunos['l3'] + df_alunos['l4']

# Cria a coluna n2
df_alunos['n2'] = df_alunos['av2']*2.5
df_alunos

,MATRICULA,Nome,l1,l2,l3,l4,av2,n2
0,20249053885,AECIO FLORINDO DE ARAUJO,0,1,1,0,2,5.0
1,20249035027,ALICE MARIA CASTRO FERRAZ,0,1,1,1,3,7.5
2,20249044966,ANA CAROLINA LIMA DE SOUSA,1,1,0,0,2,5.0
3,20249046405,BRUNA COSTA DA SILVA,1,1,1,0,3,7.5
4,20189026600,BRUNO DOS SANTOS BARBOSA DANTAS,1,1,1,0,3,7.5
5,20249049757,EZEQUIAS DA SILVA SANTOS,0,1,1,1,3,7.5
6,20249039545,FELIPE SILVA ROCHA,0,1,1,0,2,5.0
7,20249045293,FRANCISCO VITORIO DA SILVA DE ANANIAS,1,1,1,0,3,7.5
8,20249035626,GABRIEL DE OLIVEIRA BARBOSA,1,1,1,0,3,7.5
9,20249046343,GABRIEL MACEDO LOPES,1,1,1,0,3,7.5
10,20249040831,GIOVANNY MENDES DE BRITO,1,1,0,0,2,5.0
11,20249028443,GUILHERME ARTHUR MATOS SALES,1,1,0,0,2,5.0
12,20249010019,ILDBERG SILVA DE SOUSA,1,1,1,0,3,7.5
13,20249034988,JOSE EDVAR NUNES DE MOURA JUNIOR,1,0,1,0,2,5.0
14,20249009250,JULIO CESAR SILVA SOUSA,1,1,0,0,2,5.0
15,20249049766,JULIO GABRIEL MELO BACELAR,0,1,0,0,1,2.5
16,20249010743,KAIO VICTOR SILVA SOUSA,1,1,1,1,4,10.0
17,20249045177,KLEBER DOS SANTOS PEREIRA,1,1,1,0,3,7.5
18,20249046245,LOURIVAL FERNANDES DE ARAUJO NETO,1,0,1,0,2,5.0
19,20249016881,LUCAS DOS SANTOS DE SALES,0,0,0,0,0,0.0
20,20249036561,LUIS SILVIO MOREIRA ALMEIDA,1,1,0,1,3,7.5
21,20249053437,LUIZ RODRIGUES DA SILVA NETO,1,1,1,1,4,10.0
22,20249041777,MARCELO OLIVEIRA SILVA,1,1,1,1,4,10.0
23,20249033120,MARCUS ELIAS GOMES BEZERRA,1,1,1,0,3,7.5
24,20249051002,MATEUS DE MOURA FERREIRA MOREIRA,0,1,1,0,2,5.0
25,20249011150,MATHEUS SARAIVA CIPRIANO DANTAS,1,1,1,0,3,7.5
26,20249011349,PAULO GUILHERME ARAUJO DA SILVA,1,1,1,0,3,7.5
27,20249048651,PAULO VENICIOS DA SILVA NASCIMENTO,0,1,1,0,2,5.0
28,20249046441,RAMON NICOLAS SILVA CEZAR,1,1,1,0,3,7.5
29,20249034075,RIAN FILIPE ARAUJO SOARES DE SOUSA,1,0,0,1,2,5.0
30,20249035573,VICTOR GABRIEL DE JESUS MATIAS VIEIRA,1,1,0,0,2,5.0

In [ ]:
# Exporta o dataframe av2 para excel
df_alunos.to_excel('av2.xlsx')

# Versão Modularizada

In [ ]:
# Configuração para exibir todas as colunas no DataFrame (opcional)
pd.set_option('display.max_columns', None)

def load_and_standardize_data(student_file_path, list_files_prefix, assessment_name):
    """
    Carrega os dados dos alunos e das listas de exercícios, padronizando os nomes.

    Args:
        student_file_path (str): Caminho do arquivo CSV com a lista de alunos.
        list_files_prefix (str): Prefixo do caminho das listas (ex: 'av1/lista').
        assessment_name (str): Nome da avaliação (ex: 'av1' ou 'av2').

    Returns:
        tuple: (df_alunos, listas_de_nomes)
            - df_alunos: DataFrame com os alunos.
            - listas_de_nomes: Lista contendo os nomes de cada lista (l1, l2, l3, l4).
    """
    # Carrega a lista de alunos e padroniza a coluna 'Nome'
    df_alunos = pd.read_csv(student_file_path)
    df_alunos = df_alunos.rename(columns={'NOME': 'Nome'})

    # Carrega as 4 listas de exercícios e extrai os nomes
    listas_de_nomes = []
    for i in range(1, 5):
        list_file = f"{list_files_prefix}{i}.csv"
        df_list = pd.read_csv(list_file)
        listas_de_nomes.append(df_list['Nome'].tolist())

    return df_alunos, listas_de_nomes

def update_list_status(df_alunos, listas_de_nomes, assessment_name):
    """
    Atualiza o DataFrame com os status de entrega das listas (0 ou 1).

    Args:
        df_alunos (pd.DataFrame): DataFrame com os alunos.
        listas_de_nomes (list): Lista contendo os nomes de cada lista.
        assessment_name (str): Nome da avaliação (ex: 'av1' ou 'av2').

    Returns:
        pd.DataFrame: DataFrame atualizado com as colunas l1, l2, l3, l4.
    """
    # Cria colunas para cada lista (l1, l2, l3, l4)
    for i in range(1, 5):
        col_name = f"l{i}"
        df_alunos[col_name] = 0

    # Atualiza o status (1 se o aluno entregou a lista)
    for i, lista in enumerate(listas_de_nomes, 1):
        col_name = f"l{i}"
        df_alunos[col_name] = df_alunos['Nome'].apply(lambda x: 1 if x in lista else 0)

    return df_alunos

def calculate_grade(df_alunos, assessment_name):
    """
    Calcula a nota da avaliação baseada nas listas entregues.

    Args:
        df_alunos (pd.DataFrame): DataFrame com os alunos.
        assessment_name (str): Nome da avaliação (ex: 'av1' ou 'av2').

    Returns:
        pd.DataFrame: DataFrame com as colunas de nota calculadas.
    """
    # Soma as listas entregues (av1 = l1 + l2 + l3 + l4)
    df_alunos[f"{assessment_name}"] = df_alunos[['l1', 'l2', 'l3', 'l4']].sum(axis=1)

    # Calcula a nota final (n1 = av1 * 2.5)
    df_alunos[f"n{assessment_name[-1]}"] = df_alunos[f"{assessment_name}"] * 2.5

    return df_alunos

def process_assessment(student_file_path, list_files_prefix, assessment_name, output_file):
    """
    Processa uma avaliação completa (carrega dados, atualiza status, calcula nota e exporta).

    Args:
        student_file_path (str): Caminho do arquivo CSV com a lista de alunos.
        list_files_prefix (str): Prefixo do caminho das listas (ex: 'av1/lista').
        assessment_name (str): Nome da avaliação (ex: 'av1' ou 'av2').
        output_file (str): Nome do arquivo Excel de saída.
    """
    # Carrega e padroniza os dados
    df_alunos, listas_de_nomes = load_and_standardize_data(student_file_path, list_files_prefix, assessment_name)

    # Atualiza o status das listas
    df_alunos = update_list_status(df_alunos, listas_de_nomes, assessment_name)

    # Calcula a nota
    df_alunos = calculate_grade(df_alunos, assessment_name)

    # Remove NaN e exporta para Excel
    df_alunos = df_alunos.fillna(0)
    df_alunos.to_excel(output_file, index=False)

    print(f"Processamento concluído. Arquivo salvo em: {output_file}")

In [ ]:
# Dados da primeira avaliação (av1)
process_assessment(
    student_file_path='alunos_pe_20251.csv',
    list_files_prefix='av1/lista',
    assessment_name='av1',
    output_file='av1.xlsx'
)

Processamento concluído. Arquivo salvo em: av1.xlsx

In [ ]:
# Dados da segunda avaliação (av2)
process_assessment(
    student_file_path='alunos_pe_20251.csv',
    list_files_prefix='av2/lista',
    assessment_name='av2',
    output_file='av2.xlsx'
)

Processamento concluído. Arquivo salvo em: av2.xlsx

# Versão POO

In [ ]:
class GradeProcessor:
    """Classe base para processamento de notas"""

    def __init__(self):
        pd.set_option('display.max_columns', None)

    def _load_student_data(self, student_file_path):
        """Carrega e padroniza os dados dos alunos"""
        df = pd.read_csv(student_file_path)
        return df.rename(columns={'NOME': 'Nome'})

    def _load_exercise_lists(self, list_files_prefix):
        """Carrega as listas de exercícios"""
        lists = []
        for i in range(1, 5):
            list_file = f"{list_files_prefix}{i}.csv"
            df_list = pd.read_csv(list_file)
            lists.append(df_list['Nome'].tolist())
        return lists

    def _update_list_status(self, df, lists):
        """Atualiza o status de entrega das listas"""
        for i in range(1, 5):
            df[f"l{i}"] = 0

        for i, exercise_list in enumerate(lists, 1):
            df[f"l{i}"] = df['Nome'].apply(lambda x: 1 if x in exercise_list else 0)
        return df

    def _calculate_grades(self, df, assessment_name):
        """Calcula as notas finais"""
        df[assessment_name] = df[['l1', 'l2', 'l3', 'l4']].sum(axis=1)
        df[f"n{assessment_name[-1]}"] = df[assessment_name] * 2.5
        return df

    def process_assessment(self, student_file_path, list_files_prefix, assessment_name, output_file):
        """Processa uma avaliação completa"""
        df = self._load_student_data(student_file_path)
        lists = self._load_exercise_lists(list_files_prefix)
        df = self._update_list_status(df, lists)
        df = self._calculate_grades(df, assessment_name)
        df = df.fillna(0)
        df.to_excel(output_file, index=False)
        print(f"Processamento concluído. Arquivo salvo em: {output_file}")


class AssessmentManager:
    """Gerencia múltiplas avaliações"""

    def __init__(self):
        self.processor = GradeProcessor()

    def run_assessments(self, assessments):
        """Executa o processamento para múltiplas avaliações"""
        for assessment in assessments:
            self.processor.process_assessment(
                student_file_path=assessment['student_file'],
                list_files_prefix=assessment['lists_prefix'],
                assessment_name=assessment['name'],
                output_file=assessment['output']
            )


# Configuração e execução
if __name__ == "__main__":
    assessments_config = [
        {
            'student_file': 'alunos_pe_20251.csv',
            'lists_prefix': 'av1/lista',
            'name': 'av1',
            'output': 'av1.xlsx'
        },
        {
            'student_file': 'alunos_pe_20251.csv',
            'lists_prefix': 'av2/lista',
            'name': 'av2',
            'output': 'av2.xlsx'
        }
    ]

    manager = AssessmentManager()
    manager.run_assessments(assessments_config)